# Generated by Django 6.0.1 on 2026-01-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["priority"]},
        ),
        migrations.AddField(
            model_name="habit",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
